### ISSUE TITLE
explore ipywidgets or similar for Zoo model selection

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/segmentation_zoo#10]

**Comment by dbuscombe-usgs** [comment]
This may make more sense now we are going down the route of providing example jupyter notebooks. Perhaps we could repurpose some code from CoastSeg @2320sharon ? (not urgent, just thinking/planning)

**Comment by 2320sharon** [comment]
I believe that would be possible if the user chose to run the model from a jupyter notebook or used a jupyter notebook to create the model card.  We could use `ipywidgets` to create interactive inputs that would be used to create the model card similarly to coastseg.
![image](https://user-images.githubusercontent.com/61564689/196267899-245b6035-f11c-4e16-b73d-38b4462639e3.png)

**Comment by dbuscombe-usgs** [comment]
This will be implemented in a simple notebook that
1. lists available models in a widget
2. allows user to select
3. applies the model to a small set of Landsat images
