### ISSUE TITLE
Implementation Notebooks

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_zoo#14]
put some example notebooks online

**Comment by ebgoldstein** [comment]
- single prediction
- prediction confidence
- TTA
- batch prediction

**Comment by dbuscombe-usgs** [comment]
- [ ]  Otsu threshold versus simple threshold (binary problems)
- [ ] speed up inference using concurrent futures e.g. https://stackoverflow.com/questions/66036272/predicting-in-parallel-using-concurrent-futures-of-tensorflow-keras-models

**Comment by dbuscombe-usgs** [comment]
- [ ]  download a Zenodo model (model selected using a widget) and use it for prediction on a Landsat image

**Comment by dbuscombe-usgs** [comment]
I'm closing this. My focus is on making tools (scripts), not examples. Feel free to reopen if/when we need
