### ISSUE TITLE
remove DO_CRF option for post-processing estimated labels in `select_model_and_batch_process_folder.py` and install yml file

### ISSUE THREAD

**Issue by dbuscombe-usgs** [Doodleverse/segmentation_zoo#16]
The `pydensecrf` package is problematic and this has been well documented on these pages.

It is not a particularly useful option for post-processing. Plus, it prevents deployment on automated servers like Hugging Face because it is a dependency of `doodleverse-utils`

It should therefore be removed from all Zoo, Gym, and Doodleverse-utils functions, as well as CoastSeg

For Zoo, it involves modifying `select_model_and_batch_process_folder.py` and install yml file

**Comment by dbuscombe-usgs** [comment]
Fixed in https://github.com/Doodleverse/segmentation_zoo/commit/e735ab4437326cf7715425f517bf9a01844e2aff

Now needs doodleverse-utils version v0.0.14 https://pypi.org/manage/project/doodleverse-utils/release/0.0.14/

see also https://github.com/Doodleverse/doodleverse_utils/issues/16

**Comment by 2320sharon** [comment]
Thank you for updating doodleverse-utils to remove the pydensecrf dependency this is going to make development and maintenance so much easier! 🎊
