### ISSUE TITLE
Downloads For Some Models are Broken

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_zoo#19]
The new way of downloading the models from zenodo using the Zenodo API works great for the new models. However the old models with the `.zip` format are not able to be downloaded. For instance when the user tries to download the model `aerial_2class_6234122` the download fails because the code cannot find  downloaded files `BEST_MODEL.txt` or any files that end with  `.h5` because all these files are in the model's zipped directory on zenodo.

choices = ['sat_RGB_2class_7384255', 'sat_5band_2class_7388008', 
            'sat_RGB_4class_6950472', 'sat_5band_4class_7344606', 
            'sat_NDWI_4class_7352859', 'sat_MNDWI_4class_7352850', 'sat_7band_4class_7358284',
            'aerial_2class_6234122', 'aerial_2class_6235090', 'ortho_2class_6410157']

The following models currently cannot be downloaded:

1. aerial_2class_6234122
2. aerial_2class_6235090
3. ortho_2class_6410157

**Comment by 2320sharon** [comment]
I'm currently working on a method to detect if the zenodo release contains a zipped directory called 'rgb.zip' and using a different method to download the zipped file and unzip it. I should have it ready tomorrow.

**Comment by ebgoldstein** [comment]
@2320sharon , can we close this now?

**Comment by 2320sharon** [comment]
Yup we can close this, thank you for the reminder.
