### ISSUE TITLE
Best Model.txt for model 'sat_RGB_2class_7384255' is incorrect

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_zoo#20]
https://zenodo.org/record/7384255#.Y465B3bMJg8
The model `sat_RGB_2class_7384255` has the incorrect .h5 file set as the best model in `BEST_MODEL.txt` it currently has the file `sat4class_rgb_512_v6_fullmodel.h5` set as the best file when it should be one of the RGB 2 class models.

**Comment by dbuscombe-usgs** [comment]
Thanks, I have uploaded the correct file and the new version is https://zenodo.org/record/7448405#.Y5yxPH3P23A
