### ISSUE TITLE
CustomSatUnet Model is missing from doodleverse_utils

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_zoo#21]
In [scripts/select_model_and_batch_process_folder.py](https://github.com/Doodleverse/segmentation_zoo/blob/25130452b06606dd3d3b0b655b5cc6d63475e38c/scripts/select_model_and_batch_process_folder.py) if  the MODEL variable read from the config file is  'satunet' the code attempts to create a `custom_satunet` model from doodleverseutils [doodleverse_utils/model_imports.py](https://github.com/Doodleverse/doodleverse_utils/blob/6c8e1adc5443c6ed567f6988580542f1c2e0a6d0/doodleverse_utils/model_imports.py), but this model doesn't exist. 

After digging through [doodleverse_utils/model_imports.py](https://github.com/Doodleverse/doodleverse_utils/blob/6c8e1adc5443c6ed567f6988580542f1c2e0a6d0/doodleverse_utils/model_imports.py) I found a model defined as `simple_satunet` so I'm going to replace the call for `custom_satunet` with `simple_satunet` for now.

**Comment by dbuscombe-usgs** [comment]
Thanks for identifying this. I think `custom_satunet` does not exist. It is only `simple_satunet` that exists. So, I believe your fix can be made permanent
