### ISSUE TITLE
Missing best model  h5 file on zenodo release for sat_5band_2class_7388008

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_zoo#23]
The model ` sat_5band_2class_7388008` is missing the h5 file ` sat4class_5d_512_v4_fullmodel.h5` which is the best model list in the best_model.txt on [zenodo](https://zenodo.org/record/7388008#.Y5Fbf3bMKkc). Can you upload this missing file to the zenodo release when you get the chance?

**Comment by 2320sharon** [comment]
I believe the title of the best h5 model should not be `sat4class_5d_512_v1_fullmodel.h5` but it should be `sat2class_5d_512_v4_fullmodel.h5` instead

**Comment by dbuscombe-usgs** [comment]
Well spotted and apologies for the mistake. I have uploaded the new file and this is the latest version: https://zenodo.org/record/7448390#.Y5ywOn3P23A
