### ISSUE TITLE
Satellite 2 class model is missing model card for 2 model class

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_zoo#28]
https://zenodo.org/record/7448405#.ZCIwPXbMKUk

The model cards included on this release are named `sat4class_rgb_512` which is the makes it look like these belong to the 4 class model when they are actually for the 2 class model. It  took me way to long to notice that there was a 4 instead of a 2 in the model card name. Is it easy to rename the files on the zenodo release?

**Comment by dbuscombe-usgs** [comment]
Here is a new release: https://zenodo.org/record/7779766#.ZCOM2Y7MLRY

**Comment by dbuscombe-usgs** [comment]
Seg Zoo script should be modified with the new DOI, as should the docs. Leaving this open as a reminder
